databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn fitnes_tracker.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL2
        fromDatabase:
          name: mysitedb
          property: postgres://mysite:ePhnslerWaDruyejAnGsb7UEc8ZZWerz@dpg-cnessv6v3ddc73ad3uk0-a/mysite_jak0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4