# Generated by Django 4.2.3 on 2023-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='current_week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
