# Generated by Django 4.2.3 on 2023-07-15 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_articlemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
