# Generated by Django 4.2.3 on 2023-07-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dailycalorieintake_remove_fitnessuser_bmr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True, verbose_name='carbohydrate grams'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.IntegerField(blank=True, null=True, verbose_name='fat grams'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='protein grams'),
        ),
    ]
