# Generated by Django 4.2.3 on 2023-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_meal_calories_alter_meal_carbohydrates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.IntegerField(blank=True, null=True, verbose_name='protein grams')),
                ('carbohydrates', models.IntegerField(blank=True, null=True, verbose_name='carbohydrate grams')),
                ('fats', models.IntegerField(blank=True, null=True, verbose_name='fat grams')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='created_by',
        ),
        migrations.AddField(
            model_name='meal',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='list_of_ingredients',
            field=models.ManyToManyField(related_name='meals', to='accounts.ingredients'),
        ),
    ]
