# Generated by Django 4.2.3 on 2023-07-30 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ingredients_remove_meal_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='age',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height in sm'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Weight in kgs'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_carbs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_fats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_protein',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
