# Generated by Django 4.2.3 on 2023-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_fitnessuser_age_alter_fitnessuser_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='list_of_ingredients',
        ),
        migrations.AddField(
            model_name='meal',
            name='list_of_ingredients',
            field=models.JSONField(default=list),
        ),
    ]
