# Generated by Django 4.2.3 on 2023-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_articlemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycalorieintake',
            name='total_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycalorieintake',
            name='total_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycalorieintake',
            name='total_protein',
            field=models.IntegerField(default=0),
        ),
    ]
