# Generated by Django 4.2.3 on 2023-08-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_dailyuserreport_daily_carbs_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_carbs_intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_intake_carbs_report', to='accounts.dailycalorieintake'),
        ),
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_fats_intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_intake_fats_report', to='accounts.dailycalorieintake'),
        ),
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_intake_calories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_intake_calories_report', to='accounts.dailycalorieintake'),
        ),
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_protein_intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_intake_protein_report', to='accounts.dailycalorieintake'),
        ),
    ]
