# Generated by Django 4.2.3 on 2023-08-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_dailyuserreport_daily_carbs_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_carbs_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_fats_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_intake_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyuserreport',
            name='daily_protein_intake',
            field=models.IntegerField(default=0),
        ),
    ]
