name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Set up PostgreSQL
        run: |
          echo "DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': ${{ secrets.DB_NAME }},
                'USER': ${{ secrets.DB_USER }},
                'PASSWORD': ${{ secrets.DB_PASSWORD }},
                'HOST': ${{ secrets.DB_HOST }},
                'PORT': ${{ secrets.DB_PORT }},
            }
          }" > fitnes_tracker/settings.py
        working-directory: ./fitnes_tracker

      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Apply Database Migrations
        run: |
             cd fitnes_tracker  
             python manage.py migrate
      - name: Collect Static Files
        run: |
          cd fitnes_tracker  
          python manage.py collectstatic --noinput
      - name: Deploy Application
        run: python manage.py runserver